-- ============================================================================
-- Copyright (C) 2020 Pierre Ardoin
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program. If not, see <http://www.gnu.org/licenses/>.
--
-- ============================================================================


-- Data file with idprof3 (APE/NAF) codes and activity
-- There is duplicate idprof3-activity-country_code but they are not loaded because of constraint

CREATE TABLE IF NOT EXISTS `llx_c_idprof3`( 
  	`rowid`				int(11) AUTO_INCREMENT,
  	`idprof3` 			VARCHAR(255) NOT NULL UNIQUE, 
  	`activity` 			VARCHAR(255) NOT NULL,   
	`country_code`      VARCHAR(255) NOT NULL,
	`active`           	TINYINT(4)    NOT NULL DEFAULT 1,

	PRIMARY KEY (`rowid`) 
)ENGINE=innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;

-- France
INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('0111Z', 'Culture de céréales (à l\'exception du riz), de légumineuses et de graines oléagineuses', 'FR', 1),
('0112Z', 'Culture du riz', 'FR', 1),
('0113Z', 'Culture de légumes, de melons, de racines et de tubercules', 'FR', 1),
('0114Z', 'Culture de la canne à sucre', 'FR', 1),
('0115Z', 'Culture du tabac', 'FR', 1),
('0116Z', 'Culture de plantes à fibres', 'FR', 1),
('0119Z', 'Autres cultures non permanentes', 'FR', 1),
('0121Z', 'Culture de la vigne', 'FR', 1),
('0122Z', 'Culture de fruits tropicaux et subtropicaux', 'FR', 1),
('0123Z', 'Culture d\'agrumes', 'FR', 1),
('0124Z', 'Culture de fruits à pépins et à noyau', 'FR', 1),
('0125Z', 'Culture d\'autres fruits d\'arbres ou d\'arbustes et de fruits à coque', 'FR', 1),
('0126Z', 'Culture de fruits oléagineux', 'FR', 1),
('0127Z', 'Culture de plantes à boissons', 'FR', 1),
('0128Z', 'Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques', 'FR', 1),
('0129Z', 'Autres cultures permanentes', 'FR', 1),
('0130Z', 'Reproduction de plantes', 'FR', 1),
('0141Z', 'Élevage de vaches laitières', 'FR', 1),
('0142Z', 'Élevage d\'autres bovins et de buffles', 'FR', 1),
('0143Z', 'Élevage de chevaux et d\'autres équidés', 'FR', 1),
('0144Z', 'Élevage de chameaux et d\'autres camélidés', 'FR', 1),
('0145Z', 'Élevage d\'ovins et de caprins', 'FR', 1),
('0146Z', 'Élevage de porcins', 'FR', 1),
('0147Z', 'Élevage de volailles', 'FR', 1),
('0149Z', 'Élevage d\'autres animaux', 'FR', 1),
('0150Z', 'Culture et élevage associés', 'FR', 1),
('0161Z', 'Activités de soutien aux cultures', 'FR', 1),
('0162Z', 'Activités de soutien à la production animale', 'FR', 1),
('0163Z', 'Traitement primaire des récoltes', 'FR', 1),
('0164Z', 'Traitement des semences', 'FR', 1),
('0170Z', 'Chasse, piégeage et services annexes', 'FR', 1),
('0210Z', 'Sylviculture et autres activités forestières', 'FR', 1),
('0220Z', 'Exploitation forestière', 'FR', 1),
('0230Z', 'Récolte de produits forestiers non ligneux poussant à l\'état sauvage', 'FR', 1),
('0240Z', 'Services de soutien à l\'exploitation forestière', 'FR', 1),
('0311Z', 'Pêche en mer', 'FR', 1),
('0312Z', 'Pêche en eau douce', 'FR', 1),
('0321Z', 'Aquaculture en mer', 'FR', 1),
('0322Z', 'Aquaculture en eau douce', 'FR', 1),
('0510Z', 'Extraction de houille', 'FR', 1),
('0520Z', 'Extraction de lignite', 'FR', 1),
('0610Z', 'Extraction de pétrole brut', 'FR', 1),
('0620Z', 'Extraction de gaz naturel', 'FR', 1),
('0710Z', 'Extraction de minerais de fer', 'FR', 1),
('0721Z', 'Extraction de minerais d\'uranium et de thorium', 'FR', 1),
('0729Z', 'Extraction d\'autres minerais de métaux non ferreux', 'FR', 1),
('0811Z', 'Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d\'ardoise', 'FR', 1),
('0812Z', 'Exploitation de gravières et sablières, extraction d\'argiles et de kaolin', 'FR', 1),
('0891Z', 'Extraction des minéraux chimiques et d\'engrais minéraux', 'FR', 1),
('0892Z', 'Extraction de tourbe', 'FR', 1),
('0893Z', 'Production de sel', 'FR', 1),
('0899Z', 'Autres activités extractives n.c.a.', 'FR', 1),
('0910Z', 'Activités de soutien à l\'extraction d\'hydrocarbures', 'FR', 1),
('0990Z', 'Activités de soutien aux autres industries extractives', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('1011Z', 'Transformation et conservation de la viande de boucherie', 'FR', 1),
('1012Z', 'Transformation et conservation de la viande de volaille', 'FR', 1),
('1013A', 'Préparation industrielle de produits à base de viande', 'FR', 1),
('1013B', 'Charcuterie', 'FR', 1),
('1020Z', 'Transformation et conservation de poisson, de crustacés et de mollusques', 'FR', 1),
('1031Z', 'Transformation et conservation de pommes de terre', 'FR', 1),
('1032Z', 'Préparation de jus de fruits et légumes', 'FR', 1),
('1039A', 'Autre transformation et conservation de légumes', 'FR', 1),
('1039B', 'Transformation et conservation de fruits', 'FR', 1),
('1041B', 'Fabrication d\'huiles et graisses raffinées', 'FR', 1),
('1042Z', 'Fabrication de margarine et graisses comestibles similaires', 'FR', 1),
('1051A', 'Fabrication de lait liquide et de produits frais', 'FR', 1),
('1051B', 'Fabrication de beurre', 'FR', 1),
('1051C', 'Fabrication de fromage', 'FR', 1),
('1051D', 'Fabrication d\'autres produits laitiers', 'FR', 1),
('1052Z', 'Fabrication de glaces et sorbets', 'FR', 1),
('1061A', 'Meunerie', 'FR', 1),
('1061B', 'Autres activités du travail des grains', 'FR', 1),
('1062Z', 'Fabrication de produits amylacés', 'FR', 1),
('1071A', 'Fabrication industrielle de pain et de pâtisserie fraîche', 'FR', 1),
('1071B', 'Cuisson de produits de boulangerie', 'FR', 1),
('1071C', 'Boulangerie et boulangerie-pâtisserie', 'FR', 1),
('1071D', 'Pâtisserie', 'FR', 1),
('1072Z', 'Fabrication de biscuits, biscottes et pâtisseries de conservation', 'FR', 1),
('1073Z', 'Fabrication de pâtes alimentaires', 'FR', 1),
('1081Z', 'Fabrication de sucre', 'FR', 1),
('1082Z', 'Fabrication de cacao, chocolat et de produits de confiserie', 'FR', 1),
('1083Z', 'Transformation du thé et du café', 'FR', 1),
('1084Z', 'Fabrication de condiments et assaisonnements', 'FR', 1),
('1085Z', 'Fabrication de plats préparés', 'FR', 1),
('1086Z', 'Fabrication d\'aliments homogénéisés et diététiques', 'FR', 1),
('1089Z', 'Fabrication d\'autres produits alimentaires n.c.a.', 'FR', 1),
('1091Z', 'Fabrication d\'aliments pour animaux de ferme', 'FR', 1),
('1092Z', 'Fabrication d\'aliments pour animaux de compagnie', 'FR', 1),
('1101Z', 'Production de boissons alcooliques distillées', 'FR', 1),
('1102A', 'Fabrication de vins effervescents', 'FR', 1),
('1102B', 'Vinification', 'FR', 1),
('1103Z', 'Fabrication de cidre et de vins de fruits', 'FR', 1),
('1104Z', 'Production d\'autres boissons fermentées non distillées', 'FR', 1),
('1105Z', 'Fabrication de bière', 'FR', 1),
('1106Z', 'Fabrication de malt', 'FR', 1),
('1107A', 'Industrie des eaux de table', 'FR', 1),
('1107B', 'Production de boissons rafraîchissantes', 'FR', 1),
('1200Z', 'Fabrication de produits à base de tabac', 'FR', 1),
('1310Z', 'Préparation de fibres textiles et filature', 'FR', 1),
('1320Z', 'Tissage', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('1330Z', 'Ennoblissement textile', 'FR', 1),
('1391Z', 'Fabrication d\'étoffes à mailles', 'FR', 1),
('1392Z', 'Fabrication d\'articles textiles, sauf habillement', 'FR', 1),
('1393Z', 'Fabrication de tapis et moquettes', 'FR', 1),
('1394Z', 'Fabrication de ficelles, cordes et filets', 'FR', 1),
('1395Z', 'Fabrication de non-tissés, sauf habillement', 'FR', 1),
('1396Z', 'Fabrication d\'autres textiles techniques et industriels', 'FR', 1),
('1399Z', 'Fabrication d\'autres textiles n.c.a.', 'FR', 1),
('1411Z', 'Fabrication de vêtements en cuir', 'FR', 1),
('1412Z', 'Fabrication de vêtements de travail', 'FR', 1),
('1413Z', 'Fabrication de vêtements de dessus', 'FR', 1),
('1414Z', 'Fabrication de vêtements de dessous', 'FR', 1),
('1419Z', 'Fabrication d\'autres vêtements et accessoires', 'FR', 1),
('1420Z', 'Fabrication d\'articles en fourrure', 'FR', 1),
('1431Z', 'Fabrication d\'articles chaussants à mailles', 'FR', 1),
('1439Z', 'Fabrication d\'autres articles à mailles', 'FR', 1),
('1511Z', 'Apprêt et tannage des cuirs ; préparation et teinture des fourrures', 'FR', 1),
('1512Z', 'Fabrication d\'articles de voyage, de maroquinerie et de sellerie', 'FR', 1),
('1520Z', 'Fabrication de chaussures', 'FR', 1),
('1610A', 'Sciage et rabotage du bois, hors imprégnation', 'FR', 1),
('1610B', 'Imprégnation du bois', 'FR', 1),
('1621Z', 'Fabrication de placage et de panneaux de bois', 'FR', 1),
('1622Z', 'Fabrication de parquets assemblés', 'FR', 1),
('1623Z', 'Fabrication de charpentes et d\'autres menuiseries', 'FR', 1),
('1624Z', 'Fabrication d\'emballages en bois', 'FR', 1),
('1629Z', 'Fabrication d\'objets divers en bois ; fabrication d\'objets en liège, vannerie et sparterie', 'FR', 1),
('1711Z', 'Fabrication de pâte à papier', 'FR', 1),
('1712Z', 'Fabrication de papier et de carton', 'FR', 1),
('1721A', 'Fabrication de carton ondulé', 'FR', 1),
('1721B', 'Fabrication de cartonnages', 'FR', 1),
('1721C', 'Fabrication d\'emballages en papier', 'FR', 1),
('1722Z', 'Fabrication d\'articles en papier à usage sanitaire ou domestique', 'FR', 1),
('1723Z', 'Fabrication d\'articles de papeterie', 'FR', 1),
('1724Z', 'Fabrication de papiers peints', 'FR', 1),
('1729Z', 'Fabrication d\'autres articles en papier ou en carton', 'FR', 1),
('1811Z', 'Imprimerie de journaux', 'FR', 1),
('1812Z', 'Autre imprimerie (labeur)', 'FR', 1),
('1813Z', 'Activités de pré-presse', 'FR', 1),
('1814Z', 'Reliure et activités connexes', 'FR', 1),
('1820Z', 'Reproduction d\'enregistrements', 'FR', 1),
('1910Z', 'Cokéfaction', 'FR', 1),
('1920Z', 'Raffinage du pétrole', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('2011Z', 'Fabrication de gaz industriels', 'FR', 1),
('2012Z', 'Fabrication de colorants et de pigments', 'FR', 1),
('2013A', 'Enrichissement et retraitement de matières nucléaires', 'FR', 1),
('2013B', 'Fabrication d\'autres produits chimiques inorganiques de base n.c.a.', 'FR', 1),
('2014Z', 'Fabrication d\'autres produits chimiques organiques de base', 'FR', 1),
('2015Z', 'Fabrication de produits azotés et d\'engrais', 'FR', 1),
('2016Z', 'Fabrication de matières plastiques de base', 'FR', 1),
('2017Z', 'Fabrication de caoutchouc synthétique', 'FR', 1),
('2020Z', 'Fabrication de pesticides et d\'autres produits agrochimiques', 'FR', 1),
('2030Z', 'Fabrication de peintures, vernis, encres et mastics', 'FR', 1),
('2041Z', 'Fabrication de savons, détergents et produits d\'entretien', 'FR', 1),
('2042Z', 'Fabrication de parfums et de produits pour la toilette', 'FR', 1),
('2051Z', 'Fabrication de produits explosifs', 'FR', 1),
('2052Z', 'Fabrication de colles', 'FR', 1),
('2053Z', 'Fabrication d\'huiles essentielles', 'FR', 1),
('2059Z', 'Fabrication d\'autres produits chimiques n.c.a.', 'FR', 1),
('2060Z', 'Fabrication de fibres artificielles ou synthétiques', 'FR', 1),
('2110Z', 'Fabrication de produits pharmaceutiques de base', 'FR', 1),
('2120Z', 'Fabrication de préparations pharmaceutiques', 'FR', 1),
('2211Z', 'Fabrication et rechapage de pneumatiques', 'FR', 1),
('2219Z', 'Fabrication d\'autres articles en caoutchouc', 'FR', 1),
('2221Z', 'Fabrication de plaques, feuilles, tubes et profilés en matières plastiques', 'FR', 1),
('2222Z', 'Fabrication d\'emballages en matières plastiques', 'FR', 1),
('2223Z', 'Fabrication d\'éléments en matières plastiques pour la construction', 'FR', 1),
('2229A', 'Fabrication de pièces techniques à base de matières plastiques', 'FR', 1),
('2229B', 'Fabrication de produits de consommation courante en matières plastiques', 'FR', 1),
('2311Z', 'Fabrication de verre plat', 'FR', 1),
('2312Z', 'Façonnage et transformation du verre plat', 'FR', 1),
('2313Z', 'Fabrication de verre creux', 'FR', 1),
('2314Z', 'Fabrication de fibres de verre', 'FR', 1),
('2319Z', 'Fabrication et façonnage d\'autres articles en verre, y compris verre technique', 'FR', 1),
('2320Z', 'Fabrication de produits réfractaires', 'FR', 1),
('2331Z', 'Fabrication de carreaux en céramique', 'FR', 1),
('2332Z', 'Fabrication de briques, tuiles et produits de construction, en terre cuite', 'FR', 1),
('2341Z', 'Fabrication d\'articles céramiques à usage domestique ou ornemental', 'FR', 1),
('2342Z', 'Fabrication d\'appareils sanitaires en céramique', 'FR', 1),
('2343Z', 'Fabrication d\'isolateurs et pièces isolantes en céramique', 'FR', 1),
('2344Z', 'Fabrication d\'autres produits céramiques à usage technique', 'FR', 1),
('2349Z', 'Fabrication d\'autres produits céramiques', 'FR', 1),
('2351Z', 'Fabrication de ciment', 'FR', 1),
('2352Z', 'Fabrication de chaux et plâtre', 'FR', 1),
('2361Z', 'Fabrication d\'éléments en béton pour la construction', 'FR', 1),
('2362Z', 'Fabrication d\'éléments en plâtre pour la construction', 'FR', 1),
('2363Z', 'Fabrication de béton prêt à l\'emploi', 'FR', 1),
('2364Z', 'Fabrication de mortiers et bétons secs', 'FR', 1),
('2365Z', 'Fabrication d\'ouvrages en fibre-ciment', 'FR', 1),
('2369Z', 'Fabrication d\'autres ouvrages en béton, en ciment ou en plâtre', 'FR', 1),
('2370Z', 'Taille, façonnage et finissage de pierres', 'FR', 1),
('2391Z', 'Fabrication de produits abrasifs', 'FR', 1),
('2399Z', 'Fabrication d\'autres produits minéraux non métalliques n.c.a.', 'FR', 1),
('2410Z', 'Sidérurgie', 'FR', 1),
('2420Z', 'Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier', 'FR', 1),
('2431Z', 'Etirage à froid de barres', 'FR', 1),
('2432Z', 'Laminage à froid de feuillards', 'FR', 1),
('2433Z', 'Profilage à froid par formage ou pliage', 'FR', 1),
('2434Z', 'Tréfilage à froid', 'FR', 1),
('2441Z', 'Production de métaux précieux', 'FR', 1),
('2442Z', 'Métallurgie de l\'aluminium', 'FR', 1),
('2443Z', 'Métallurgie du plomb, du zinc ou de l\'étain', 'FR', 1),
('2444Z', 'Métallurgie du cuivre', 'FR', 1),
('2445Z', 'Métallurgie des autres métaux non ferreux', 'FR', 1),
('2446Z', 'élaboration et transformation de matières nucléaires', 'FR', 1),
('2451Z', 'Fonderie de fonte', 'FR', 1),
('2452Z', 'Fonderie d\'acier', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('2453Z', 'Fonderie de métaux légers', 'FR', 1),
('2454Z', 'Fonderie d\'autres métaux non ferreux', 'FR', 1),
('2511Z', 'Fabrication de structures métalliques et de parties de structures', 'FR', 1),
('2512Z', 'Fabrication de portes et fenêtres en métal', 'FR', 1),
('2521Z', 'Fabrication de radiateurs et de chaudières pour le chauffage central', 'FR', 1),
('2529Z', 'Fabrication d\'autres réservoirs, citernes et conteneurs métalliques', 'FR', 1),
('2530Z', 'Fabrication de générateurs de vapeur, à l\'exception des chaudières pour le chauffage central', 'FR', 1),
('2540Z', 'Fabrication d\'armes et de munitions', 'FR', 1),
('2550A', 'Forge, estampage, matriçage ; métallurgie des poudres', 'FR', 1),
('2550B', 'Découpage, emboutissage', 'FR', 1),
('2561Z', 'Traitement et revêtement des métaux', 'FR', 1),
('2562A', 'Décolletage', 'FR', 1),
('2562B', 'Mécanique industrielle', 'FR', 1),
('2571Z', 'Fabrication de coutellerie', 'FR', 1),
('2572Z', 'Fabrication de serrures et de ferrures', 'FR', 1),
('2573A', 'Fabrication de moules et modèles', 'FR', 1),
('2573B', 'Fabrication d\'autres outillages', 'FR', 1),
('2591Z', 'Fabrication de fûts et emballages métalliques similaires', 'FR', 1),
('2592Z', 'Fabrication d\'emballages métalliques légers', 'FR', 1),
('2593Z', 'Fabrication d\'articles en fils métalliques, de chaînes et de ressorts', 'FR', 1),
('2594Z', 'Fabrication de vis et de boulons', 'FR', 1),
('2599A', 'Fabrication d\'articles métalliques ménagers', 'FR', 1),
('2599B', 'Fabrication d\'autres articles métalliques', 'FR', 1),
('2611Z', 'Fabrication de composants électroniques', 'FR', 1),
('2612Z', 'Fabrication de cartes électroniques assemblées', 'FR', 1),
('2620Z', 'Fabrication d\'ordinateurs et d\'équipements périphériques', 'FR', 1),
('2630Z', 'Fabrication d\'équipements de communication', 'FR', 1),
('2640Z', 'Fabrication de produits électroniques grand public', 'FR', 1),
('2651A', 'Fabrication d\'équipements d\'aide à la navigation', 'FR', 1),
('2651B', 'Fabrication d\'instrumentation scientifique et technique', 'FR', 1),
('2652Z', 'Horlogerie', 'FR', 1),
('2660Z', 'Fabrication d\'équipements d\'irradiation médicale, d\'équipements électromédicaux et électrothérapeutiques', 'FR', 1),
('2670Z', 'Fabrication de matériels optique et photographique', 'FR', 1),
('2680Z', 'Fabrication de supports magnétiques et optiques', 'FR', 1),
('2711Z', 'Fabrication de moteurs, génératrices et transformateurs électriques', 'FR', 1),
('2712Z', 'Fabrication de matériel de distribution et de commande électrique', 'FR', 1),
('2720Z', 'Fabrication de piles et d\'accumulateurs électriques', 'FR', 1),
('2731Z', 'Fabrication de câbles de fibres optiques', 'FR', 1),
('2732Z', 'Fabrication d\'autres fils et câbles électroniques ou électriques', 'FR', 1),
('2733Z', 'Fabrication de matériel d\'installation électrique', 'FR', 1),
('2740Z', 'Fabrication d\'appareils d\'éclairage électrique', 'FR', 1),
('2751Z', 'Fabrication d\'appareils électroménagers', 'FR', 1),
('2752Z', 'Fabrication d\'appareils ménagers non électriques', 'FR', 1),
('2790Z', 'Fabrication d\'autres matériels électriques', 'FR', 1),
('2811Z', 'Fabrication de moteurs et turbines, à l\'exception des moteurs d\'avions et de véhicules', 'FR', 1),
('2812Z', 'Fabrication d\'équipements hydrauliques et pneumatiques', 'FR', 1),
('2813Z', 'Fabrication d\'autres pompes et compresseurs', 'FR', 1),
('2814Z', 'Fabrication d\'autres articles de robinetterie', 'FR', 1),
('2815Z', 'Fabrication d\'engrenages et d\'organes mécaniques de transmission', 'FR', 1),
('2821Z', 'Fabrication de fours et brûleurs', 'FR', 1),
('2822Z', 'Fabrication de matériel de levage et de manutention', 'FR', 1),
('2823Z', 'Fabrication de machines et d\'équipements de bureau (à l\'exception des ordinateurs et équipements périphériques)', 'FR', 1),
('2824Z', 'Fabrication d\'outillage portatif à moteur incorporé', 'FR', 1),
('2825Z', 'Fabrication d\'équipements aérauliques et frigorifiques industriels', 'FR', 1),
('2829A', 'Fabrication d\'équipements d\'emballage, de conditionnement et de pesage', 'FR', 1),
('2829B', 'Fabrication d\'autres machines d\'usage général', 'FR', 1),
('2830Z', 'Fabrication de machines agricoles et forestières', 'FR', 1),
('2841Z', 'Fabrication de machines-outils pour le travail des métaux', 'FR', 1),
('2849Z', 'Fabrication d\'autres machines-outils', 'FR', 1),
('2891Z', 'Fabrication de machines pour la métallurgie', 'FR', 1),
('2892Z', 'Fabrication de machines pour l\'extraction ou la construction', 'FR', 1),
('2893Z', 'Fabrication de machines pour l\'industrie agro-alimentaire', 'FR', 1),
('2894Z', 'Fabrication de machines pour les industries textiles', 'FR', 1),
('2895Z', 'Fabrication de machines pour les industries du papier et du carton', 'FR', 1),
('2896Z', 'Fabrication de machines pour le travail du caoutchouc ou des plastiques', 'FR', 1),
('2899A', 'Fabrication de machines d\'imprimerie', 'FR', 1),
('2899B', 'Fabrication d\'autres machines spécialisées', 'FR', 1),
('2910Z', 'Construction de véhicules automobiles', 'FR', 1),
('2920Z', 'Fabrication de carrosseries et remorques', 'FR', 1),
('2931Z', 'Fabrication d\'équipements électriques et électroniques automobiles', 'FR', 1),
('2932Z', 'Fabrication d\'autres équipements automobiles', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('3011Z', 'Construction de navires et de structures flottantes', 'FR', 1),
('3012Z', 'Construction de bateaux de plaisance', 'FR', 1),
('3020Z', 'Construction de locomotives et d\'autre matériel ferroviaire roulant', 'FR', 1),
('3030Z', 'Construction aéronautique et spatiale', 'FR', 1),
('3040Z', 'Construction de véhicules militaires de combat', 'FR', 1),
('3091Z', 'Fabrication de motocycles', 'FR', 1),
('3092Z', 'Fabrication de bicyclettes et de véhicules pour invalides', 'FR', 1),
('3099Z', 'Fabrication d\'autres équipements de transport n.c.a.', 'FR', 1),
('3101Z', 'Fabrication de meubles de bureau et de magasin', 'FR', 1),
('3102Z', 'Fabrication de meubles de cuisine', 'FR', 1),
('3103Z', 'Fabrication de matelas', 'FR', 1),
('3109A', 'Fabrication de sièges d\'ameublement d\'intérieur', 'FR', 1),
('3109B', 'Fabrication d\'autres meubles et industries connexes de l\'ameublement', 'FR', 1),
('3211Z', 'Frappe de monnaie', 'FR', 1),
('3212Z', 'Fabrication d\'articles de joaillerie et bijouterie', 'FR', 1),
('3213Z', 'Fabrication d\'articles de bijouterie fantaisie et articles similaires', 'FR', 1),
('3220Z', 'Fabrication d\'instruments de musique', 'FR', 1),
('3230Z', 'Fabrication d\'articles de sport', 'FR', 1),
('3240Z', 'Fabrication de jeux et jouets', 'FR', 1),
('3250A', 'Fabrication de matériel médico-chirurgical et dentaire', 'FR', 1),
('3250B', 'Fabrication de lunettes', 'FR', 1),
('3291Z', 'Fabrication d\'articles de brosserie', 'FR', 1),
('3299Z', 'Autres activités manufacturières n.c.a.', 'FR', 1),
('3311Z', 'Réparation d\'ouvrages en métaux', 'FR', 1),
('3312Z', 'Réparation de machines et équipements mécaniques', 'FR', 1),
('3313Z', 'Réparation de matériels électroniques et optiques', 'FR', 1),
('3314Z', 'Réparation d\'équipements électriques', 'FR', 1),
('3315Z', 'Réparation et maintenance navale', 'FR', 1),
('3316Z', 'Réparation et maintenance d\'aéronefs et d\'engins spatiaux', 'FR', 1),
('3317Z', 'Réparation et maintenance d\'autres équipements de transport', 'FR', 1),
('3319Z', 'Réparation d\'autres équipements', 'FR', 1),
('3320A', 'Installation de structures métalliques, chaudronnées et de tuyauterie', 'FR', 1),
('3320B', 'Installation de machines et équipements mécaniques', 'FR', 1),
('3320C', 'Conception d\'ensemble et assemblage sur site industriel d\'équipements de contrôle des processus industriels', 'FR', 1),
('3320D', 'Installation d\'équipements électriques, de matériels électroniques et optiques ou d\'autres matériels', 'FR', 1),
('3511Z', 'Production d\'électricité', 'FR', 1),
('3512Z', 'Transport d\'électricité', 'FR', 1),
('3513Z', 'Distribution d\'électricité', 'FR', 1),
('3514Z', 'Commerce d\'électricité', 'FR', 1),
('3521Z', 'Production de combustibles gazeux', 'FR', 1),
('3522Z', 'Distribution de combustibles gazeux par conduites', 'FR', 1),
('3523Z', 'Commerce de combustibles gazeux par conduites', 'FR', 1),
('3530Z', 'Production et distribution de vapeur et d\'air conditionné', 'FR', 1),
('3600Z', 'Captage, traitement et distribution d\'eau', 'FR', 1),
('3700Z', 'Collecte et traitement des eaux usées', 'FR', 1),
('3811Z', 'Collecte des déchets non dangereux', 'FR', 1),
('3812Z', 'Collecte des déchets dangereux', 'FR', 1),
('3821Z', 'Traitement et élimination des déchets non dangereux', 'FR', 1),
('3822Z', 'Traitement et élimination des déchets dangereux', 'FR', 1),
('3831Z', 'Démantèlement d\'épaves', 'FR', 1),
('3832Z', 'Récupération de déchets triés', 'FR', 1),
('3900Z', 'Dépollution et autres services de gestion des déchets', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('4110A', 'Promotion immobilière de logements', 'FR', 1),
('4110B', 'Promotion immobilière de bureaux', 'FR', 1),
('4110C', 'Promotion immobilière d\'autres bâtiments', 'FR', 1),
('4110D', 'Supports juridiques de programmes', 'FR', 1),
('4120A', 'Construction de maisons individuelles', 'FR', 1),
('4120B', 'Construction d\'autres bâtiments', 'FR', 1),
('4211Z', 'Construction de routes et autoroutes', 'FR', 1),
('4212Z', 'Construction de voies ferrées de surface et souterraines', 'FR', 1),
('4213A', 'Construction d\'ouvrages d\'art', 'FR', 1),
('4213B', 'Construction et entretien de tunnels', 'FR', 1),
('4221Z', 'Construction de réseaux pour fluides', 'FR', 1),
('4222Z', 'Construction de réseaux électriques et de télécommunications', 'FR', 1),
('4291Z', 'Construction d\'ouvrages maritimes et fluviaux', 'FR', 1),
('4299Z', 'Construction d\'autres ouvrages de génie civil n.c.a.', 'FR', 1),
('4311Z', 'Travaux de démolition', 'FR', 1),
('4312A', 'Travaux de terrassement courants et travaux préparatoires', 'FR', 1),
('4312B', 'Travaux de terrassement spécialisés ou de grande masse', 'FR', 1),
('4313Z', 'Forages et sondages', 'FR', 1),
('4321A', 'Travaux d\'installation électrique dans tous locaux', 'FR', 1),
('4321B', 'Travaux d\'installation électrique sur la voie publique', 'FR', 1),
('4322A', 'Travaux d\'installation d\'eau et de gaz en tous locaux', 'FR', 1),
('4322B', 'Travaux d\'installation d\'équipements thermiques et de climatisation', 'FR', 1),
('4329A', 'Travaux d\'isolation', 'FR', 1),
('4329B', 'Autres travaux d\'installation n.c.a.', 'FR', 1),
('4331Z', 'Travaux de plâtrerie', 'FR', 1),
('4332A', 'Travaux de menuiserie bois et pvc', 'FR', 1),
('4332B', 'Travaux de menuiserie métallique et serrurerie', 'FR', 1),
('4332C', 'Agencement de lieux de vente', 'FR', 1),
('4333Z', 'Travaux de revêtement des sols et des murs', 'FR', 1),
('4334Z', 'Travaux de peinture et vitrerie', 'FR', 1),
('4339Z', 'Autres travaux de finition', 'FR', 1),
('4391A', 'Travaux de charpente', 'FR', 1),
('4391B', 'Travaux de couverture par éléments', 'FR', 1),
('4399A', 'Travaux d\'étanchéification', 'FR', 1),
('4399B', 'Travaux de montage de structures métalliques', 'FR', 1),
('4399C', 'Travaux de maçonnerie générale et gros oeuvre de bâtiment', 'FR', 1),
('4399D', 'Autres travaux spécialisés de construction', 'FR', 1),
('4399E', 'Location avec opérateur de matériel de construction', 'FR', 1),
('4511Z', 'Commerce de voitures et de véhicules automobiles légers', 'FR', 1),
('4519Z', 'Commerce d\'autres véhicules automobiles', 'FR', 1),
('4520A', 'Entretien et réparation de véhicules automobiles légers', 'FR', 1),
('4520B', 'Entretien et réparation d\'autres véhicules automobiles', 'FR', 1),
('4531Z', 'Commerce de gros d\'équipements automobiles', 'FR', 1),
('4532Z', 'Commerce de détail d\'équipements automobiles', 'FR', 1),
('4540Z', 'Commerce et réparation de motocycles', 'FR', 1),
('4611Z', 'Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et', 'FR', 1),
('4612A', 'Centrales d\'achat de carburant', 'FR', 1),
('4612B', 'Autres intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques', 'FR', 1),
('4613Z', 'Intermédiaires du commerce en bois et matériaux de construction', 'FR', 1),
('4614Z', 'Intermédiaires du commerce en machines, équipements industriels, navires et avions', 'FR', 1),
('4615Z', 'Intermédiaires du commerce en meubles, articles de ménage et quincaillerie', 'FR', 1),
('4616Z', 'Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir', 'FR', 1),
('4617A', 'Centrales d\'achat alimentaires', 'FR', 1),
('4617B', 'Autres intermédiaires du commerce en denrées, boissons et tabac', 'FR', 1),
('4618Z', 'Intermédiaires spécialisés dans le commerce d\'autres produits spécifiques', 'FR', 1),
('4619A', 'Centrales d\'achat non alimentaires', 'FR', 1),
('4619B', 'Autres intermédiaires du commerce en produits divers', 'FR', 1),
('4621Z', 'Commerce de gros de céréales, de tabac non manufacturé, de semences et d\'aliments pour le bétail', 'FR', 1),
('4622Z', 'Commerce de gros de fleurs et plantes', 'FR', 1),
('4623Z', 'Commerce de gros d\'animaux vivants', 'FR', 1),
('4624Z', 'Commerce de gros de cuirs et peaux', 'FR', 1),
('4631Z', 'Commerce de gros de fruits et légumes', 'FR', 1),
('4632A', 'Commerce de gros de viandes de boucherie', 'FR', 1),
('4632B', 'Commerce de gros de produits à base de viande', 'FR', 1),
('4632C', 'Commerce de gros de volailles et gibier', 'FR', 1),
('4633Z', 'Commerce de gros de produits laitiers, oeufs, huiles et matières grasses comestibles', 'FR', 1),
('4634Z', 'Commerce de gros de boissons', 'FR', 1),
('4635Z', 'Commerce de gros de produits à base de tabac', 'FR', 1),
('4636Z', 'Commerce de gros de sucre, chocolat et confiserie', 'FR', 1),
('4637Z', 'Commerce de gros de café, thé, cacao et épices', 'FR', 1),
('4638A', 'Commerce de gros de poissons, crustacés et mollusques', 'FR', 1),
('4638B', 'Commerce de gros alimentaire spécialisé divers', 'FR', 1),
('4639A', 'Commerce de gros de produits surgelés', 'FR', 1),
('4639B', 'Commerce de gros alimentaire non spécialisé', 'FR', 1),
('4641Z', 'Commerce de gros de textiles', 'FR', 1),
('4642Z', 'Commerce de gros d\'habillement et de chaussures', 'FR', 1),
('4643Z', 'Commerce de gros d\'appareils électroménagers', 'FR', 1),
('4644Z', 'Commerce de gros de vaisselle, verrerie et produits d\'entretien', 'FR', 1),
('4645Z', 'Commerce de gros de parfumerie et de produits de beauté', 'FR', 1),
('4646Z', 'Commerce de gros de produits pharmaceutiques', 'FR', 1),
('4647Z', 'Commerce de gros de meubles, de tapis et d\'appareils d\'éclairage', 'FR', 1),
('4648Z', 'Commerce de gros d\'articles d\'horlogerie et de bijouterie', 'FR', 1),
('4649Z', 'Commerce de gros d\'autres biens domestiques', 'FR', 1),
('4651Z', 'Commerce de gros d\'ordinateurs, d\'équipements informatiques périphériques et de logiciels', 'FR', 1),
('4652Z', 'Commerce de gros de composants et d\'équipements électroniques et de télécommunication', 'FR', 1),
('4661Z', 'Commerce de gros de matériel agricole', 'FR', 1),
('4662Z', 'Commerce de gros de machines-outils', 'FR', 1),
('4663Z', 'Commerce de gros de machines pour l\'extraction, la construction et le génie civil', 'FR', 1),
('4664Z', 'Commerce de gros de machines pour l\'industrie textile et l\'habillement', 'FR', 1),
('4665Z', 'Commerce de gros de mobilier de bureau', 'FR', 1),
('4666Z', 'Commerce de gros d\'autres machines et équipements de bureau', 'FR', 1),
('4669A', 'Commerce de gros de matériel électrique', 'FR', 1),
('4669B', 'Commerce de gros de fournitures et équipements industriels divers', 'FR', 1),
('4669C', 'Commerce de gros de fournitures et équipements divers pour le commerce et les services', 'FR', 1),
('4671Z', 'Commerce de gros de combustibles et de produits annexes', 'FR', 1),
('4672Z', 'Commerce de gros de minerais et métaux', 'FR', 1),
('4673A', 'Commerce de gros de bois et de matériaux de construction', 'FR', 1),
('4673B', 'Commerce de gros d\'appareils sanitaires et de produits de décoration', 'FR', 1),
('4674A', 'Commerce de gros de quincaillerie', 'FR', 1),
('4674B', 'Commerce de gros de fournitures pour la plomberie et le chauffage', 'FR', 1),
('4675Z', 'Commerce de gros de produits chimiques', 'FR', 1),
('4676Z', 'Commerce de gros d\'autres produits intermédiaires', 'FR', 1),
('4677Z', 'Commerce de gros de déchets et débris', 'FR', 1),
('4690Z', 'Commerce de gros non spécialisé', 'FR', 1),
('4711A', 'Commerce de détail de produits surgelés', 'FR', 1),
('4711B', 'Commerce d\'alimentation générale', 'FR', 1),
('4711C', 'Supérettes', 'FR', 1),
('4711D', 'Supermarchés', 'FR', 1),
('4711E', 'Magasins multi-commerces', 'FR', 1),
('4711F', 'Hypermarchés', 'FR', 1),
('4719A', 'Grands magasins', 'FR', 1),
('4719B', 'Autres commerces de détail en magasin non spécialisé', 'FR', 1),
('4721Z', 'Commerce de détail de fruits et légumes en magasin spécialisé', 'FR', 1),
('4722Z', 'Commerce de détail de viandes et de produits à base de viande en magasin spécialisé', 'FR', 1),
('4723Z', 'Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé', 'FR', 1),
('4724Z', 'Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé', 'FR', 1),
('4725Z', 'Commerce de détail de boissons en magasin spécialisé', 'FR', 1),
('4726Z', 'Commerce de détail de produits à base de tabac en magasin spécialisé', 'FR', 1),
('4729Z', 'Autres commerces de détail alimentaires en magasin spécialisé', 'FR', 1),
('4730Z', 'Commerce de détail de carburants en magasin spécialisé', 'FR', 1),
('4741Z', 'Commerce de détail d\'ordinateurs, d\'unités périphériques et de logiciels en magasin spécialisé', 'FR', 1),
('4742Z', 'Commerce de détail de matériels de télécommunication en magasin spécialisé', 'FR', 1),
('4743Z', 'Commerce de détail de matériels audio et vidéo en magasin spécialisé', 'FR', 1),
('4751Z', 'Commerce de détail de textiles en magasin spécialisé', 'FR', 1),
('4752A', 'Commerce de détail de quincaillerie, peintures et verres en petites surfaces (moins de 400 m²)', 'FR', 1),
('4752B', 'Commerce de détail de quincaillerie, peintures et verres en grandes surfaces (400 m² et plus)', 'FR', 1),
('4753Z', 'Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé', 'FR', 1),
('4754Z', 'Commerce de détail d\'appareils électroménagers en magasin spécialisé', 'FR', 1),
('4759A', 'Commerce de détail de meubles', 'FR', 1),
('4759B', 'Commerce de détail d\'autres équipements du foyer', 'FR', 1),
('4761Z', 'Commerce de détail de livres en magasin spécialisé', 'FR', 1),
('4762Z', 'Commerce de détail de journaux et papeterie en magasin spécialisé', 'FR', 1),
('4763Z', 'Commerce de détail d\'enregistrements musicaux et vidéo en magasin spécialisé', 'FR', 1),
('4764Z', 'Commerce de détail d\'articles de sport en magasin spécialisé', 'FR', 1),
('4765Z', 'Commerce de détail de jeux et jouets en magasin spécialisé', 'FR', 1),
('4771Z', 'Commerce de détail d\'habillement en magasin spécialisé', 'FR', 1),
('4772A', 'Commerce de détail de la chaussure', 'FR', 1),
('4772B', 'Commerce de détail de maroquinerie et d\'articles de voyage', 'FR', 1),
('4773Z', 'Commerce de détail de produits pharmaceutiques en magasin spécialisé', 'FR', 1),
('4774Z', 'Commerce de détail d\'articles médicaux et orthopédiques en magasin spécialisé', 'FR', 1),
('4775Z', 'Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé', 'FR', 1),
('4776Z', 'Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux', 'FR', 1),
('4777Z', 'Commerce de détail d\'articles d\'horlogerie et de bijouterie en magasin spécialisé', 'FR', 1),
('4778A', 'Commerces de détail d\'optique', 'FR', 1),
('4778B', 'Commerces de détail de charbons et combustibles', 'FR', 1),
('4778C', 'Autres commerces de détail spécialisés divers', 'FR', 1),
('4779Z', 'Commerce de détail de biens d\'occasion en magasin', 'FR', 1),
('4781Z', 'Commerce de détail alimentaire sur éventaires et marchés', 'FR', 1),
('4782Z', 'Commerce de détail de textiles, d\'habillement et de chaussures sur éventaires et marchés', 'FR', 1),
('4789Z', 'Autres commerces de détail sur éventaires et marchés', 'FR', 1),
('4791A', 'Vente à distance sur catalogue général', 'FR', 1),
('4791B', 'Vente à distance sur catalogue spécialisé', 'FR', 1),
('4799A', 'Vente à domicile', 'FR', 1),
('4799B', 'Vente par automates et autres commerces de détail hors magasin, éventaires ou marchés n.c.a.', 'FR', 1),
('4910Z', 'Transport ferroviaire interurbain de voyageurs', 'FR', 1),
('4920Z', 'Transports ferroviaires de fret', 'FR', 1),
('4931Z', 'Transports urbains et suburbains de voyageurs', 'FR', 1),
('4932Z', 'Transports de voyageurs par taxis', 'FR', 1),
('4939A', 'Transports routiers réguliers de voyageurs', 'FR', 1),
('4939B', 'Autres transports routiers de voyageurs', 'FR', 1),
('4939C', 'Téléphériques et remontées mécaniques', 'FR', 1),
('4941A', 'Transports routiers de fret interurbains', 'FR', 1),
('4941B', 'Transports routiers de fret de proximité', 'FR', 1),
('4941C', 'Location de camions avec chauffeur', 'FR', 1),
('4942Z', 'Services de déménagement', 'FR', 1),
('4950Z', 'Transports par conduites', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('5010Z', 'Transports maritimes et côtiers de passagers', 'FR', 1),
('5020Z', 'Transports maritimes et côtiers de fret', 'FR', 1),
('5030Z', 'Transports fluviaux de passagers', 'FR', 1),
('5040Z', 'Transports fluviaux de fret', 'FR', 1),
('5110Z', 'Transports aériens de passagers', 'FR', 1),
('5121Z', 'Transports aériens de fret', 'FR', 1),
('5122Z', 'Transports spatiaux', 'FR', 1),
('5210A', 'Entreposage et stockage frigorifique', 'FR', 1),
('5210B', 'Entreposage et stockage non frigorifique', 'FR', 1),
('5221Z', 'Services auxiliaires des transports terrestres', 'FR', 1),
('5222Z', 'Services auxiliaires des transports par eau', 'FR', 1),
('5223Z', 'Services auxiliaires des transports aériens', 'FR', 1),
('5224A', 'Manutention portuaire', 'FR', 1),
('5224B', 'Manutention non portuaire', 'FR', 1),
('5229A', 'Messagerie, fret express', 'FR', 1),
('5229B', 'Affrètement et organisation des transports', 'FR', 1),
('5310Z', 'Activités de poste dans le cadre d\'une obligation de service universel', 'FR', 1),
('5320Z', 'Autres activités de poste et de courrier', 'FR', 1),
('5510Z', 'Hôtels et hébergement similaire', 'FR', 1),
('5520Z', 'Hébergement touristique et autre hébergement de courte durée', 'FR', 1),
('5530Z', 'Terrains de camping et parcs pour caravanes ou véhicules de loisirs', 'FR', 1),
('5590Z', 'Autres hébergements', 'FR', 1),
('5610A', 'Restauration traditionnelle', 'FR', 1),
('5610B', 'Cafétérias et autres libres-services', 'FR', 1),
('5610C', 'Restauration de type rapide', 'FR', 1),
('5621Z', 'Services des traiteurs', 'FR', 1),
('5629A', 'Restauration collective sous contrat', 'FR', 1),
('5629B', 'Autres services de restauration n.c.a.', 'FR', 1),
('5630Z', 'Débits de boissons', 'FR', 1),
('5811Z', 'Édition de livres', 'FR', 1),
('5812Z', 'Édition de répertoires et de fichiers d\'adresses', 'FR', 1),
('5813Z', 'Édition de journaux', 'FR', 1),
('5814Z', 'Édition de revues et périodiques', 'FR', 1),
('5819Z', 'Autres activités d\'édition', 'FR', 1),
('5821Z', 'Édition de jeux électroniques', 'FR', 1),
('5829A', 'Édition de logiciels système et de réseau', 'FR', 1),
('5829B', 'Edition de logiciels outils de développement et de langages', 'FR', 1),
('5829C', 'Edition de logiciels applicatifs', 'FR', 1),
('5911A', 'Production de films et de programmes pour la télévision', 'FR', 1),
('5911B', 'Production de films institutionnels et publicitaires', 'FR', 1),
('5911C', 'Production de films pour le cinéma', 'FR', 1),
('5912Z', 'Post-production de films cinématographiques, de vidéo et de programmes de télévision', 'FR', 1),
('5913A', 'Distribution de films cinématographiques', 'FR', 1),
('5913B', 'Edition et distribution vidéo', 'FR', 1),
('5914Z', 'Projection de films cinématographiques', 'FR', 1),
('5920Z', 'Enregistrement sonore et édition musicale', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('6010Z', 'Édition et diffusion de programmes radio', 'FR', 1),
('6020A', 'Edition de chaînes généralistes', 'FR', 1),
('6020B', 'Edition de chaînes thématiques', 'FR', 1),
('6110Z', 'Télécommunications filaires', 'FR', 1),
('6120Z', 'Télécommunications sans fil', 'FR', 1),
('6130Z', 'Télécommunications par satellite', 'FR', 1),
('6190Z', 'Autres activités de télécommunication', 'FR', 1),
('6201Z', 'Programmation informatique', 'FR', 1),
('6202A', 'Conseil en systèmes et logiciels informatiques', 'FR', 1),
('6202B', 'Tierce maintenance de systèmes et d\'applications informatiques', 'FR', 1),
('6203Z', 'Gestion d\'installations informatiques', 'FR', 1),
('6209Z', 'Autres activités informatiques', 'FR', 1),
('6311Z', 'Traitement de données, hébergement et activités connexes', 'FR', 1),
('6312Z', 'Portails internet', 'FR', 1),
('6391Z', 'Activités des agences de presse', 'FR', 1),
('6399Z', 'Autres services d\'information n.c.a.', 'FR', 1),
('6411Z', 'Activités de banque centrale', 'FR', 1),
('6419Z', 'Autres intermédiations monétaires', 'FR', 1),
('6420Z', 'Activités des sociétés holding', 'FR', 1),
('6430Z', 'Fonds de placement et entités financières similaires', 'FR', 1),
('6491Z', 'Crédit-bail', 'FR', 1),
('6492Z', 'Autre distribution de crédit', 'FR', 1),
('6499Z', 'Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.', 'FR', 1),
('6511Z', 'Assurance vie', 'FR', 1),
('6512Z', 'Autres assurances', 'FR', 1),
('6520Z', 'Réassurance', 'FR', 1),
('6530Z', 'Caisses de retraite', 'FR', 1),
('6611Z', 'Administration de marchés financiers', 'FR', 1),
('6612Z', 'Courtage de valeurs mobilières et de marchandises', 'FR', 1),
('6619A', 'Supports juridiques de gestion de patrimoine mobilier', 'FR', 1),
('6619B', 'Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.', 'FR', 1),
('6621Z', 'évaluation des risques et dommages', 'FR', 1),
('6622Z', 'Activités des agents et courtiers d\'assurances', 'FR', 1),
('6629Z', 'Autres activités auxiliaires d\'assurance et de caisses de retraite', 'FR', 1),
('6630Z', 'Gestion de fonds', 'FR', 1),
('6810Z', 'Activités des marchands de biens immobiliers', 'FR', 1),
('6820A', 'Location de logements', 'FR', 1),
('6820B', 'Location de terrains et d\'autres biens immobiliers', 'FR', 1),
('6831Z', 'Agences immobilières', 'FR', 1),
('6832A', 'Administration d\'immeubles et autres biens immobiliers', 'FR', 1),
('6832B', 'Supports juridiques de gestion de patrimoine immobilier', 'FR', 1),
('6910Z', 'Activités juridiques', 'FR', 1),
('6920Z', 'Activités comptables', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('7010Z', 'Activités des sièges sociaux', 'FR', 1),
('7021Z', 'Conseil en relations publiques et communication', 'FR', 1),
('7022Z', 'Conseil pour les affaires et autres conseils de gestion', 'FR', 1),
('7111Z', 'Activités d\'architecture', 'FR', 1),
('7112A', 'Activité des géomètres', 'FR', 1),
('7112B', 'Ingénierie, études techniques', 'FR', 1),
('7120A', 'Contrôle technique automobile', 'FR', 1),
('7120B', 'Analyses, essais et inspections techniques', 'FR', 1),
('7211Z', 'Recherche-développement en biotechnologie', 'FR', 1),
('7219Z', 'Recherche-développement en autres sciences physiques et naturelles', 'FR', 1),
('7220Z', 'Recherche-développement en sciences humaines et sociales', 'FR', 1),
('7311Z', 'Activités des agences de publicité', 'FR', 1),
('7312Z', 'Régie publicitaire de médias', 'FR', 1),
('7320Z', 'études de marché et sondages', 'FR', 1),
('7410Z', 'Activités spécialisées de design', 'FR', 1),
('7420Z', 'Activités photographiques', 'FR', 1),
('7430Z', 'Traduction et interprétation', 'FR', 1),
('7490A', 'Activité des économistes de la construction', 'FR', 1),
('7490B', 'Activités spécialisées, scientifiques et techniques diverses', 'FR', 1),
('7500Z', 'Activités vétérinaires', 'FR', 1),
('7711A', 'Location de courte durée de voitures et de véhicules automobiles légers', 'FR', 1),
('7711B', 'Location de longue durée de voitures et de véhicules automobiles légers', 'FR', 1),
('7712Z', 'Location et location-bail de camions', 'FR', 1),
('7721Z', 'Location et location-bail d\'articles de loisirs et de sport', 'FR', 1),
('7722Z', 'Location de vidéocassettes et disques vidéo', 'FR', 1),
('7729Z', 'Location et location-bail d\'autres biens personnels et domestiques', 'FR', 1),
('7731Z', 'Location et location-bail de machines et équipements agricoles', 'FR', 1),
('7732Z', 'Location et location-bail de machines et équipements pour la construction', 'FR', 1),
('7733Z', 'Location et location-bail de machines de bureau et de matériel informatique', 'FR', 1),
('7734Z', 'Location et location-bail de matériels de transport par eau', 'FR', 1),
('7735Z', 'Location et location-bail de matériels de transport aérien', 'FR', 1),
('7739Z', 'Location et location-bail d\'autres machines, équipements et biens matériels n.c.a.', 'FR', 1),
('7740Z', 'Location-bail de propriété intellectuelle et de produits similaires, à l\'exception des oeuvres soumises à copyright', 'FR', 1),
('7810Z', 'Activités des agences de placement de main-d\'oeuvre', 'FR', 1),
('7820Z', 'Activités des agences de travail temporaire', 'FR', 1),
('7830Z', 'Autre mise à disposition de ressources humaines', 'FR', 1),
('7911Z', 'Activités des agences de voyage', 'FR', 1),
('7912Z', 'Activités des voyagistes', 'FR', 1),
('7990Z', 'Autres services de réservation et activités connexes', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('8010Z', 'Activités de sécurité privée', 'FR', 1),
('8020Z', 'Activités liées aux systèmes de sécurité', 'FR', 1),
('8030Z', 'Activités d\'enquête', 'FR', 1),
('8110Z', 'Activités combinées de soutien lié aux bâtiments', 'FR', 1),
('8121Z', 'Nettoyage courant des bâtiments', 'FR', 1),
('8122Z', 'Autres activités de nettoyage des bâtiments et nettoyage industriel', 'FR', 1),
('8129A', 'Désinfection, désinsectisation, dératisation', 'FR', 1),
('8129B', 'Autres activités de nettoyage n.c.a.', 'FR', 1),
('8130Z', 'Services d\'aménagement paysager', 'FR', 1),
('8211Z', 'Services administratifs combinés de bureau', 'FR', 1),
('8219Z', 'Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau', 'FR', 1),
('8220Z', 'Activités de centres d\'appels', 'FR', 1),
('8230Z', 'Organisation de foires, salons professionnels et congrès', 'FR', 1),
('8291Z', 'Activités des agences de recouvrement de factures et des sociétés d\'information financière sur la clientèle', 'FR', 1),
('8292Z', 'Activités de conditionnement', 'FR', 1),
('8299Z', 'Autres activités de soutien aux entreprises n.c.a.', 'FR', 1),
('8411Z', 'Administration publique générale', 'FR', 1),
('8412Z', 'Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux, autre que sécurité sociale', 'FR', 1),
('8413Z', 'Administration publique (tutelle) des activités économiques', 'FR', 1),
('8421Z', 'Affaires étrangères', 'FR', 1),
('8422Z', 'Défense', 'FR', 1),
('8423Z', 'Justice', 'FR', 1),
('8424Z', 'Activités d\'ordre public et de sécurité', 'FR', 1),
('8425Z', 'Services du feu et de secours', 'FR', 1),
('8430A', 'Activités générales de sécurité sociale', 'FR', 1),
('8430B', 'Gestion des retraites complémentaires', 'FR', 1),
('8430C', 'Distribution sociale de revenus', 'FR', 1),
('8510Z', 'Enseignement pré-primaire', 'FR', 1),
('8520Z', 'Enseignement primaire', 'FR', 1),
('8531Z', 'Enseignement secondaire général', 'FR', 1),
('8532Z', 'Enseignement secondaire technique ou professionnel', 'FR', 1),
('8541Z', 'Enseignement post-secondaire non supérieur', 'FR', 1),
('8542Z', 'Enseignement supérieur', 'FR', 1),
('8551Z', 'Enseignement de disciplines sportives et d\'activités de loisirs', 'FR', 1),
('8552Z', 'Enseignement culturel', 'FR', 1),
('8553Z', 'Enseignement de la conduite', 'FR', 1),
('8559A', 'Formation continue d\'adultes', 'FR', 1),
('8559B', 'Autres enseignements', 'FR', 1),
('8560Z', 'Activités de soutien à l\'enseignement', 'FR', 1),
('8610Z', 'Activités hospitalières', 'FR', 1),
('8621Z', 'Activité des médecins généralistes', 'FR', 1),
('8622A', 'Activités de radiodiagnostic et de radiothérapie', 'FR', 1),
('8622B', 'Activités chirurgicales', 'FR', 1),
('8622C', 'Autres activités des médecins spécialistes', 'FR', 1),
('8623Z', 'Pratique dentaire', 'FR', 1),
('8690A', 'Ambulances', 'FR', 1),
('8690B', 'Laboratoires d\'analyses médicales', 'FR', 1),
('8690C', 'Centres de collecte et banques d\'organes', 'FR', 1),
('8690D', 'Activités des infirmiers et des sages-femmes', 'FR', 1),
('8690E', 'Activités des professionnels de la rééducation, de l\'appareillage et des pédicures-podologues', 'FR', 1),
('8690F', 'Activités de santé humaine non classées ailleurs', 'FR', 1),
('8710A', 'Hébergement médicalisé pour personnes âgées', 'FR', 1),
('8710B', 'Hébergement médicalisé pour enfants handicapés', 'FR', 1),
('8710C', 'Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé', 'FR', 1),
('8720A', 'Hébergement social pour handicapés mentaux et malades mentaux', 'FR', 1),
('8720B', 'Hébergement social pour toxicomanes', 'FR', 1),
('8730A', 'Hébergement social pour personnes âgées', 'FR', 1),
('8730B', 'Hébergement social pour handicapés physiques', 'FR', 1),
('8790A', 'Hébergement social pour enfants en difficultés', 'FR', 1),
('8790B', 'Hébergement social pour adultes et familles en difficultés et autre hébergement social', 'FR', 1),
('8810A', 'Aide à domicile', 'FR', 1),
('8810B', 'Accueil ou accompagnement sans hébergement d\'adultes handicapés ou de personnes âgées', 'FR', 1),
('8810C', 'Aide par le travail', 'FR', 1),
('8891A', 'Accueil de jeunes enfants', 'FR', 1),
('8891B', 'Accueil ou accompagnement sans hébergement d\'enfants handicapés', 'FR', 1),
('8899A', 'Autre accueil ou accompagnement sans hébergement d\'enfants et d\'adolescents', 'FR', 1),
('8899B', 'Action sociale sans hébergement n.c.a.', 'FR', 1);

INSERT IGNORE INTO llx_c_idprof3 (idprof3, activity, country_code, active) VALUES
('9001Z', 'Arts du spectacle vivant', 'FR', 1),
('9002Z', 'Activités de soutien au spectacle vivant', 'FR', 1),
('9003A', 'Création artistique relevant des arts plastiques', 'FR', 1),
('9003B', 'Autre création artistique', 'FR', 1),
('9004Z', 'Gestion de salles de spectacles', 'FR', 1),
('9101Z', 'Gestion des bibliothèques et des archives', 'FR', 1),
('9102Z', 'Gestion des musées', 'FR', 1),
('9103Z', 'Gestion des sites et monuments historiques et des attractions touristiques similaires', 'FR', 1),
('9104Z', 'Gestion des jardins botaniques et zoologiques et des réserves naturelles', 'FR', 1),
('9200Z', 'Organisation de jeux de hasard et d\'argent', 'FR', 1),
('9311Z', 'Gestion d\'installations sportives', 'FR', 1),
('9312Z', 'Activités de clubs de sports', 'FR', 1),
('9313Z', 'Activités des centres de culture physique', 'FR', 1),
('9319Z', 'Autres activités liées au sport', 'FR', 1),
('9321Z', 'Activités des parcs d\'attractions et parcs à thèmes', 'FR', 1),
('9329Z', 'Autres activités récréatives et de loisirs', 'FR', 1),
('9411Z', 'Activités des organisations patronales et consulaires', 'FR', 1),
('9412Z', 'Activités des organisations professionnelles', 'FR', 1),
('9420Z', 'Activités des syndicats de salariés', 'FR', 1),
('9491Z', 'Activités des organisations religieuses', 'FR', 1),
('9492Z', 'Activités des organisations politiques', 'FR', 1),
('9499Z', 'Autres organisations fonctionnant par adhésion volontaire', 'FR', 1),
('9511Z', 'Réparation d\'ordinateurs et d\'équipements périphériques', 'FR', 1),
('9512Z', 'Réparation d\'équipements de communication', 'FR', 1),
('9521Z', 'Réparation de produits électroniques grand public', 'FR', 1),
('9522Z', 'Réparation d\'appareils électroménagers et d\'équipements pour la maison et le jardin', 'FR', 1),
('9523Z', 'Réparation de chaussures et d\'articles en cuir', 'FR', 1),
('9524Z', 'Réparation de meubles et d\'équipements du foyer', 'FR', 1),
('9525Z', 'Réparation d\'articles d\'horlogerie et de bijouterie', 'FR', 1),
('9529Z', 'Réparation d\'autres biens personnels et domestiques', 'FR', 1),
('9601A', 'Blanchisserie-teinturerie de gros', 'FR', 1),
('9601B', 'Blanchisserie-teinturerie de détail', 'FR', 1),
('9602A', 'Coiffure', 'FR', 1),
('9602B', 'Soins de beauté', 'FR', 1),
('9603Z', 'Services funéraires', 'FR', 1),
('9604Z', 'Entretien corporel', 'FR', 1),
('9609Z', 'Autres services personnels n.c.a.', 'FR', 1),
('9700Z', 'Activités des ménages en tant qu\'employeurs de personnel domestique', 'FR', 1),
('9810Z', 'Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre', 'FR', 1),
('9820Z', 'Activités indifférenciées des ménages en tant que producteurs de services pour usage propre', 'FR', 1),
('9900Z', 'Activités des organisations et organismes extraterritoriaux', 'FR', 1);











